name: Testes do Portal ECLB

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

             
    steps:
      - name: Shutdown Ubuntu MySQL (SUDO)
        run: sudo service mysql stop
      
      - name: Set up MariaDB
        uses: getong/mariadb-action@v1.11
        with:
          # host port: 3306 # Optional, default value is 3306. The port of host
          # container port: 3306 # Optional, default value is 3306. The port of container
          character set server: 'utf8' # Optional, default value is 'utf8mb4'. The '--character-set-server' option for mysqld
          collation server: 'utf8_general_ci' # Optional, default value is 'utf8mb4_general_ci'. The '--collation-server' option for mysqld
          # mariadb version: '11.3.0' # Optional, default value is "latest". The version of the MariaDB
          # mysql database: 'eclb_dev' # Optional, default value is "test". The specified database which will be create
          # mysql root password: "aluno" # Required if "mysql user" is empty, default is empty. The root superuser password
          # mysql user: 'root' # Required if "mysql root password" is empty, default is empty. The superuser for the specified database. Can use secrets, too
          # mysql password: 'aluno' 
        
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Creating on MariaDB
        run: mysql -h 127.0.0.1 -u root < db/script/eclb_dev.sql

      - name: Showing all tables
        run: | 
              mysql -h 127.0.0.1 -u root -e "
                use eclb_dev;
                show tables;
                ALTER USER 'root'@'172.17.0.1' IDENTIFIED BY 'aluno';
              "

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2'

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test
    
