name: Testes do Portal ECLB

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:latest
        ports:
          - 3306:3306
        env:
          MARIADB_ROOT_PASSWORD: root
          MARIADB_DATABASE: eclb_dev
          MARIADB_USER: root
          MARIADB_PASSWORD: aluno

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Listing diretories
        run: ls

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2'

      - name: Install dependencies
        run: flutter pub get

      - name: Create Database Schema
        run: mysql -u root -paluno eclb_dev < db/script/eclb_dev.sql

      - name: Run tests
        run: flutter test
    
