name: Testes do Portal ECLB

on: [push, pull_request]

jobs:

  test:
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:latest
        ports:
          - 3306:3306
        env:
          MARIADB_ROOT_PASSWORD: root
          MARIADB_DATABASE: eclb_dev
          MARIADB_USER: root
          MARIADB_PASSWORD: aluno

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.22.2'

    - name: Flutter Pub Get
      run: flutter pub get

    - name: Wait for MariaDB to be ready
      run: |
        until mariadb -h 127.0.0.1 -P 3306 -u root -p aluno -e "SELECT 1"; do
          echo "Waiting for MariaDB..."
          sleep 1
        done
    
